In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

from scipy.optimize import minimize
from sklearn.preprocessing import PolynomialFeatures

pd.set_option('display.notebook_repr_html', False)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 150)
pd.set_option('display.max_seq_items', None)
 
#%config InlineBackend.figure_formats = {'pdf',}
%matplotlib inline

import seaborn as sns
sns.set_context('notebook')
sns.set_style('white')

In [3]:
from sklearn.feature_extraction import DictVectorizer
import csv
import sys
from sklearn import preprocessing
from sklearn import tree
from sklearn.externals.six import StringIO

In [4]:
with open("example.csv","w") as out:
    writer = csv.writer(out)
    header = ['RID','age','income','student','credit_rating','buys_computer']
    writer.writerow(header)
    rowdata_1=['1','youth','high','no','fair','no']
    writer.writerow(rowdata_1)
    rowdata_2=['2','youth','high','no','excellent','no']
    writer.writerow(rowdata_2)
    rowdata_3=['3','middle_aged','high','no','fair','yes']
    writer.writerow(rowdata_3)
    rowdata_4=['4','senior','medium','no','fair','yes']
    writer.writerow(rowdata_4)
    rowdata_5=['5','senior','low','yes','fair','yes']
    writer.writerow(rowdata_5)
    rowdata_6=['6','senior','low','yes','excellent','no']
    writer.writerow(rowdata_6)
    rowdata_7=['7','middle_aged','low','yes','excellent','yes']
    writer.writerow(rowdata_7)
    rowdata_8=['8','youth','medium','no','fair','no']
    writer.writerow(rowdata_8)
    rowdata_9=['9','youth','low','yes','fair','yes']
    writer.writerow(rowdata_9)
    rowdata_10=['10','senior','medium','yes','fair','yes']
    writer.writerow(rowdata_10)
    rowdata_11=['11','youth','medium','yes','excellent','yes']
    writer.writerow(rowdata_11)
    rowdata_12=['12','middle_aged','medium','no','excellent','yes']
    writer.writerow(rowdata_12)
    rowdata_13=['13','middle_aged','high','yes','fair','yes']
    writer.writerow(rowdata_13)
    rowdata_14=['14','senior','medium','no','excellent','no']
    writer.writerow(rowdata_14)

In [5]:
allElectionicsData = open(r"example.csv","rb")
reader = csv.reader(allElectionicsData)
headers = reader.next()

In [6]:
headers

['RID', 'age', 'income', 'student', 'credit_rating', 'buys_computer']

In [7]:
featureList = []
labelList = []
for row in reader:
    print row
    labelList.append(row[len(row)-1])
    rowDic={}
    for i in range(1,len(row)-1):
        rowDic[headers[i]]=row[i]
    featureList.append(rowDic)
    #已经没有第一行了，reader的特性读取完后接着下一个位置开始读取,所以输出没有开始的headers

['1', 'youth', 'high', 'no', 'fair', 'no']
['2', 'youth', 'high', 'no', 'excellent', 'no']
['3', 'middle_aged', 'high', 'no', 'fair', 'yes']
['4', 'senior', 'medium', 'no', 'fair', 'yes']
['5', 'senior', 'low', 'yes', 'fair', 'yes']
['6', 'senior', 'low', 'yes', 'excellent', 'no']
['7', 'middle_aged', 'low', 'yes', 'excellent', 'yes']
['8', 'youth', 'medium', 'no', 'fair', 'no']
['9', 'youth', 'low', 'yes', 'fair', 'yes']
['10', 'senior', 'medium', 'yes', 'fair', 'yes']
['11', 'youth', 'medium', 'yes', 'excellent', 'yes']
['12', 'middle_aged', 'medium', 'no', 'excellent', 'yes']
['13', 'middle_aged', 'high', 'yes', 'fair', 'yes']
['14', 'senior', 'medium', 'no', 'excellent', 'no']


In [8]:
print featureList
print labelList
#从csv中提取featureList,lebelList

[{'credit_rating': 'fair', 'age': 'youth', 'student': 'no', 'income': 'high'}, {'credit_rating': 'excellent', 'age': 'youth', 'student': 'no', 'income': 'high'}, {'credit_rating': 'fair', 'age': 'middle_aged', 'student': 'no', 'income': 'high'}, {'credit_rating': 'fair', 'age': 'senior', 'student': 'no', 'income': 'medium'}, {'credit_rating': 'fair', 'age': 'senior', 'student': 'yes', 'income': 'low'}, {'credit_rating': 'excellent', 'age': 'senior', 'student': 'yes', 'income': 'low'}, {'credit_rating': 'excellent', 'age': 'middle_aged', 'student': 'yes', 'income': 'low'}, {'credit_rating': 'fair', 'age': 'youth', 'student': 'no', 'income': 'medium'}, {'credit_rating': 'fair', 'age': 'youth', 'student': 'yes', 'income': 'low'}, {'credit_rating': 'fair', 'age': 'senior', 'student': 'yes', 'income': 'medium'}, {'credit_rating': 'excellent', 'age': 'youth', 'student': 'yes', 'income': 'medium'}, {'credit_rating': 'excellent', 'age': 'middle_aged', 'student': 'no', 'income': 'medium'}, {'cr

In [9]:
vec = DictVectorizer() #vector Feature
dummyX = vec.fit_transform(featureList).toarray() #把特征值标准化为0，1组成的向量
print dummyX
print vec.get_feature_names()
print "labelList:"+str(labelList)

[[ 0.  0.  1.  0.  1.  1.  0.  0.  1.  0.]
 [ 0.  0.  1.  1.  0.  1.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  1.  1.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  1.  0.  0.  1.  1.  0.]
 [ 0.  1.  0.  0.  1.  0.  1.  0.  0.  1.]
 [ 0.  1.  0.  1.  0.  0.  1.  0.  0.  1.]
 [ 1.  0.  0.  1.  0.  0.  1.  0.  0.  1.]
 [ 0.  0.  1.  0.  1.  0.  0.  1.  1.  0.]
 [ 0.  0.  1.  0.  1.  0.  1.  0.  0.  1.]
 [ 0.  1.  0.  0.  1.  0.  0.  1.  0.  1.]
 [ 0.  0.  1.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  0.  0.  1.  0.  0.  0.  1.  1.  0.]
 [ 1.  0.  0.  0.  1.  1.  0.  0.  0.  1.]
 [ 0.  1.  0.  1.  0.  0.  0.  1.  1.  0.]]
['age=middle_aged', 'age=senior', 'age=youth', 'credit_rating=excellent', 'credit_rating=fair', 'income=high', 'income=low', 'income=medium', 'student=no', 'student=yes']
labelList:['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']


In [10]:
lb = preprocessing.LabelBinarizer()
dummyY = lb.fit_transform(labelList)
print "dummyY:"+str(dummyY)

dummyY:[[0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]]


In [11]:
clf = tree.DecisionTreeClassifier(criterion="entropy")
#创建一个分类器，entropy决定了用ID3算法
clf = clf.fit(dummyX,dummyY)
print "clf:"+str(clf)

clf:DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')


In [14]:
#可视化
#需要pydot，pydotplus是兼容版本
#同时还需要Graphviz,去www.graphviz.org官网下载
import os     
os.environ["PATH"] += os.pathsep + 'C:/Python27/Scripts/Graphviz2.38/bin/'
import pydotplus
dot_data = StringIO()
tree.export_graphviz(clf,
                    out_file=dot_data,
                    filled=True,
                    rounded=True,
                    impurity=False)
print dot_data.getvalue()
help(pydotplus.graph_from_dot_data)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())#pydot无法完成
graph.write_pdf("viz.pdf")
#出现GraphViz's executables not found
#查阅资料后发现,原来我没有安装GraphViz's executables.
#我是用pip安装的Graphviz,但是Graphviz不是一个python tool，你仍然需要安装GraphViz's executables.
#windows安装网址：http://www.graphviz.org/Download_windows.php，下载graphviz-2.38-zip，并把\bin文件夹添加到环境变量

digraph Tree {
node [shape=box, style="filled, rounded", color="black", fontname=helvetica] ;
edge [fontname=helvetica] ;
0 [label="X[0] <= 0.5\nsamples = 14\nvalue = [5, 9]", fillcolor="#399de571"] ;
1 [label="X[8] <= 0.5\nsamples = 10\nvalue = [5, 5]", fillcolor="#e5813900"] ;
0 -> 1 [labeldistance=2.5, labelangle=45, headlabel="True"] ;
2 [label="X[3] <= 0.5\nsamples = 5\nvalue = [1, 4]", fillcolor="#399de5bf"] ;
1 -> 2 ;
3 [label="samples = 3\nvalue = [0, 3]", fillcolor="#399de5ff"] ;
2 -> 3 ;
4 [label="X[1] <= 0.5\nsamples = 2\nvalue = [1, 1]", fillcolor="#e5813900"] ;
2 -> 4 ;
5 [label="samples = 1\nvalue = [0, 1]", fillcolor="#399de5ff"] ;
4 -> 5 ;
6 [label="samples = 1\nvalue = [1, 0]", fillcolor="#e58139ff"] ;
4 -> 6 ;
7 [label="X[1] <= 0.5\nsamples = 5\nvalue = [4, 1]", fillcolor="#e58139bf"] ;
1 -> 7 ;
8 [label="samples = 3\nvalue = [3, 0]", fillcolor="#e58139ff"] ;
7 -> 8 ;
9 [label="X[3] <= 0.5\nsamples = 2\nvalue = [1, 1]", fillcolor="#e5813900"] ;
7 -> 9 ;
10 [label="sam

True

In [13]:
'''
tree.export_graphviz()
Parameters:

decision_tree : decision tree classifier

The decision tree to be exported to GraphViz.



out_file : file object or string, optional (default=’tree.dot’)

Handle or name of the output file. If None, the result is returned as a string. This will the default from version 0.20.



max_depth : int, optional (default=None)

The maximum depth of the representation. If None, the tree is fully generated.



feature_names : list of strings, optional (default=None)

Names of each of the features.



class_names : list of strings, bool or None, optional (default=None)

Names of each of the target classes in ascending numerical order. Only relevant for classification and not supported for multi-output. If True, shows a symbolic representation of the class name.



label : {‘all’, ‘root’, ‘none’}, optional (default=’all’)

Whether to show informative labels for impurity, etc. Options include ‘all’ to show at every node, ‘root’ to show only at the top root node, or ‘none’ to not show at any node.



filled : bool, optional (default=False)

When set to True, paint nodes to indicate majority class for classification, extremity of values for regression, or purity of node for multi-output.



leaves_parallel : bool, optional (default=False)

When set to True, draw all leaf nodes at the bottom of the tree.



impurity : bool, optional (default=True)

When set to True, show the impurity at each node.



node_ids : bool, optional (default=False)

When set to True, show the ID number on each node.



proportion : bool, optional (default=False)

When set to True, change the display of ‘values’ and/or ‘samples’ to be proportions and percentages respectively.



rotate : bool, optional (default=False)

When set to True, orient tree left to right rather than top-down.



rounded : bool, optional (default=False)

When set to True, draw node boxes with rounded corners and use Helvetica fonts instead of Times-Roman.



special_characters : bool, optional (default=False)

When set to False, ignore special characters for PostScript compatibility.
 

Returns:

dot_data : string

String representation of the input tree in GraphViz dot format. Only returned if out_file is None.


New in version 0.18.
'''



'\ntree.export_graphviz()\nParameters:\n\ndecision_tree : decision tree classifier\n\nThe decision tree to be exported to GraphViz.\n\n\n\nout_file : file object or string, optional (default=\xe2\x80\x99tree.dot\xe2\x80\x99)\n\nHandle or name of the output file. If None, the result is returned as a string. This will the default from version 0.20.\n\n\n\nmax_depth : int, optional (default=None)\n\nThe maximum depth of the representation. If None, the tree is fully generated.\n\n\n\nfeature_names : list of strings, optional (default=None)\n\nNames of each of the features.\n\n\n\nclass_names : list of strings, bool or None, optional (default=None)\n\nNames of each of the target classes in ascending numerical order. Only relevant for classification and not supported for multi-output. If True, shows a symbolic representation of the class name.\n\n\n\nlabel : {\xe2\x80\x98all\xe2\x80\x99, \xe2\x80\x98root\xe2\x80\x99, \xe2\x80\x98none\xe2\x80\x99}, optional (default=\xe2\x80\x99all\xe2\x80\x

In [15]:
#预测
oneRowX = dummyX[0,:]
newRowX = oneRowX
newRowX[0] = 1
newRowX[2] = 0
print "newRowX:"+str(newRowX)

newRowX:[ 1.  0.  0.  0.  1.  1.  0.  0.  1.  0.]


In [16]:
predictY = clf.predict(newRowX)
print "predictY:"+str(predictY)

predictY:[1]


c:\python27\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
